after_script: greenkeeper-lockfile-upload
before_install: npm install npm@latest --global
before_script: greenkeeper-lockfile-update
env:
  global:
    - secure: cmnZnrXAWdUbjNqyqEkTV6APhAz5mp+G0CF0AvbuGGfZvPtE47RiRoRswqbVIHdLayClqjnDINCU7m0huUq/+3zujKz5HfB4eBdwwGrniFuVbVB0eZ1N3/z+ZeGajkrrBkP0C/W0b7M6h/gjIJG3siWfcmwolTkRaFiNGyRh7Dm9j68VOiTluAq9eN6EiKG1nO9CkAIin4nGqNgkH/MT38SAXTAmde5Fr8+JP3+JOASv5s2UK0HvQ+EjjbZ1spRyVUBnlX6kHFVOr2ug3VyNIqxrN4Qfw8j8OREIQpOUXx7HQ7X9reB0q5GBb1TUwX7mgJp8MGCUSii6jRbKVISsUcZZPLEW1DLjzBx7hb2jbUuuJtfK2MDmfXxa9sQjVJu+inMfaYZUn2hZ3zEHodDuuVd/aOqzbAQNu20BNetkbXp7ng2zOjbIfuOlVTwyLUEv3slQ8BjclsS+ba61Qx7nqJBKETBYqBVQX6DfNWG1PowQASJvodWoSCz9Vf7GTXy3hdODWYJ+r78ivGK1rFFOze/wkkhQZXMvnwUBO8zeYpBOnnghojjF9Jf3kau1jTGWI4VxHVUQ+SdBH3Ev28pUQ89YgOG55DkMAb6YN4+Wy749li4zOw3Rt1D6NOVvrEFmeWupS86lbsMxlM/G1vPUV1VG88si/CGDsUN7r+9JgZ8=
install: npm ci || npm i
language: node_js
node_js: 6
sudo: false
